# Workflow to build and deploy to your GitHub Pages repo.

# Edit your project details here.
# Remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!
env:
  githubEmail: danielsuttonp@gmail.com
  deployToRepo: henry-jenkins-website

name: Github Pages Astro CI

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [master]

  schedule:
    - cron: "30 6 * * 0" # 6:30 AM UTC Sunday (5:30 PM Melbourne time during standard time)

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Add permissions for GITHUB_TOKEN
permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better commit messages

      # Setup Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Install dependencies with npm
      - name: Install dependencies
        run: npm ci

      # Build the project and add .nojekyll file to suppress default behaviour
      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll
          echo 'henryjenkins.com.au' > ./dist/CNAME

      # Push to your pages repo
      - name: Push to pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dist"
          destination-github-username: ${{ github.actor }}
          destination-repository-name: ${{ env.deployToRepo }}
          user-email: ${{ env.githubEmail }}
          user-name: ${{ github.actor }}
          commit-message: "Deploy from ${{ github.sha }}"
          target-branch: gh-pages

      # Keep repository active with manual keepalive
      - name: Keep repository active
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create an empty commit to show activity
          git commit --allow-empty -m "🤖 Automated keepalive commit"
          git push origin master
